flask:
  build: ./flask
  volumes:
    - ./site:/usr/src/site
  expose:
    - "5000"
nginx:
  image: nginx:latest
  links:
    - flask
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
